# Generated by Django 4.0.1 on 2022-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam'), (2, 'không xác định')], default=2),
        ),
    ]
