# Generated by Django 4.0.1 on 2022-01-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bank_card',
            field=models.IntegerField(null=True),
        ),
    ]
