# Generated by Django 4.0.1 on 2022-01-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('infomation', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
