# Generated by Django 4.0.1 on 2022-01-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='home',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reviewer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
    ]
