# Generated by Django 4.0.1 on 2022-01-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_product_comment_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
