# Generated by Django 4.0.1 on 2022-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_product_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='describe',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
